### ISSUE TITLE
Open external links a new tab

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms-demo#363]
The "Bekijk bij bron" opens in the current window. As this actions is only a side step in the search process I would recommend to open external links like these in a new tab.

**Comment by ddeboer** [comment]
Auto-opening links in new tabs is bad user experience, in my opinion. Users know how to use the back button to get back. Would it help to add an icon that makes clear the ‘Bekijk bij bron’ points to an external site?

**Comment by EnnoMeijers** [comment]
Ok, that would be helpful.
