### ISSUE TITLE
Sort narrower and broader labels

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms-demo#364]
Some terms have a lot of narrower (or broader?) terms. It would be helpful to sort them alphabetically, see for example https://termennetwerk.netwerkdigitaalerfgoed.nl/lookup?uri=http://vocab.getty.edu/aat/300010900

**Comment by ddeboer** [comment]
Sorting the term results themselves has been added to the API (netwerk-digitaal-erfgoed/network-of-terms-api#68). Should we do the same for narrower, broader and related or do you prefer to see them sorted only in the demonstrator?

**Comment by EnnoMeijers** [comment]
I agree, this would fit better in the API and is useful for all applications using the API.

**Comment by ddeboer** [comment]
Continued in https://github.com/netwerk-digitaal-erfgoed/network-of-terms-api/issues/380.
