### ISSUE TITLE
Search with 'queryMode': 'no terms found'?

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/network-of-terms-demo#413]
Has the new [`queryMode` functionality](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-demo/commit/da61fc3c7c2c7c86371937cf12c6953038675beb) already been released to the [frontend](https://termennetwerk.netwerkdigitaalerfgoed.nl/)?

If so: if I search for [`Wagemans, G.A.M.` in RKDartists](https://termennetwerk.netwerkdigitaalerfgoed.nl/?q=Asten,+Els+C.M.+van&datasets=https://data.netwerkdigitaalerfgoed.nl/rkd/rkdartists/sparql), then the message `no terms found` is displayed. But if I search for the same search word via the [API](https://termennetwerk-api.netwerkdigitaalerfgoed.nl/graphiql)...

```graphql
query {
  terms(
    sources: ["https://data.netwerkdigitaalerfgoed.nl/rkd/rkdartists/sparql"],
    query: "Wagemans, G.A.M.",
    queryMode: OPTIMIZED   # Forwards-compatible query type.
  ) {
    result {
      __typename
      ... on Terms {
        terms {
          uri
          prefLabel
          altLabel
          hiddenLabel
          scopeNote
          seeAlso
        }
      }
      ... on Error {
        message
      }
    }
  }
}
```

...then I get 1 term in return (as expected).

**Comment by ddeboer** [comment]
Yes, it has been released; the demonstrato gives [a result for Wagemans](https://termennetwerk.netwerkdigitaalerfgoed.nl/?q=Wagemans,+G.A.M.&datasets=https://data.netwerkdigitaalerfgoed.nl/rkd/rkdartists/sparql). There was a [separate issue with RKDartists](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-catalog/pull/118) but that too was already fixed when you reported this issue (and shouldn’t be related anyway).

Can you try your query again and see if behaves now?

**Comment by sdevalk** [comment]
Working perfectly now! :)
