### ISSUE TITLE
Make result order clearer in how cards are displayed

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/network-of-terms-demo#50]
The term result cards now seem to be rendered in columns from top to bottom, which obscures the alphabetical ordering of the results (https://github.com/netwerk-digitaal-erfgoed/network-of-terms-api/issues/68).

**Comment by EnnoMeijers** [comment]
Can we give this issue some priority? It is really annoying to have to scroll from top to bottom in long result lists.
