### ISSUE TITLE
only value for altLabel shown

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms-demo#6]
When searching for "Jan Wolkers" in NTA only one altLabel value is shown in the result for "Wolkers, Jan (1925-2007)". According to the GraphQL result the following values should be shown:
            "altLabel": [
              "Jan Wolkers",
              "Bolkers, Gian",
              "Wolkers, Jan",
              "Volkers, Jan",
              "Wolkers, Jan Hendrik"
            ],

**Comment by ddeboer** [comment]
Fixed in 05d7610cb3f52f524b7faaf7d15c694af87b8539.
