### ISSUE TITLE
Dev version fails to run

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms-demo#866]
Running 'npm run dev' fails with the following error in the browser:

`Uncaught SyntaxError: missing name after . operator`

This seems to to be an known issue see https://stackoverflow.com/questions/76530650/node-modules-broken-when-using-vite-react-apollo-client

**Comment by ddeboer** [comment]
Thanks for investigating this! JavaScript/Node and its dependencies can be really be messy at times.
