### ISSUE TITLE
Thesaurus Selection Aid

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/network-of-terms-demo#985]
To help heritage organisation select the right terminology source(s) to use, a new "selection aid" function in the NoT demonstrator would be needed.

Prototype by @rschalkrce:
![image](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-demo/assets/101820/1a573928-183c-45e9-b41c-debc24b7381b)

For this function to work the terminology source descriptions (such as https://github.com/netwerk-digitaal-erfgoed/network-of-terms/blob/master/packages/network-of-terms-catalog/catalog/datasets/cht.jsonld) should be expanded with a `schema:genre` property with one or more values from a controlled-by-us (or standard) vocabulary (in Dutch and English).

The [GraphQL API](https://github.com/netwerk-digitaal-erfgoed/network-of-terms/tree/master/packages/network-of-terms-graphql) should be expanded in order for the demonstrator to query terminology source (datasets) on one or more selected 'genres'.

Additionally, it would be nice to give more information about a terminology source via this selection aid or an overview of terminology sources page, like `schema:mainEntityOfPage` and `schema:description`. In the future, information from the Dataset KG about terminology source usage could be included (or used for sorting).

**Comment by ddeboer** [comment]
Discussed today and decided:

* to store the genres in the dataset descriptions
* to add a separate page to the demonstrator with the genres and for each, a list of terminology sources for that genre
* on that page, for each genre, add a link to take those terminology sources to the current search interface.

**Comment by rschalkrce** [comment]
Would it be an option to consider `schema.org` Types for the genres? Upside: follows NDE recommendations. Downside: difficult to add new types. 

We could use `sdo:`

- Event
- Person (also MusicGroup)
- Place
- Organization
- Thing (perhaps too generic)
- Material 
- CreativeWork (for types of publication, e.g. Brinkman)
- Occupation
- Action (for activities)

We miss `sdo` types for genres:
- Techniques
- Physical attributes/ characteristics (perhaps `sdo:PropertyValue` could do)
- Periods in time (but could consider `sdo:Time`)
- Genre (for Iconclass)

**Comment by rschalkrce** [comment]
Thanks for your reply @EnnoMeijers . I did not find a vocab suitable for our use yet. Perhaps we should make our own genre list using PoolParty? Benefit is that we can expand it when needed. I can maintain the list.

**Comment by rschalkrce** [comment]
@ddeboer I've started with a genre list that we can use to categorize the datasets: https://data.cultureelerfgoed.nl/termennetwerk/onderwerpen.html 

Let me know if this works for you. If you can adapt the json-ld datasets descriptions, I can add the genres per dataset.

**Comment by rschalkrce** [comment]
Hi @ddeboer do you have enough to work with to implement a genre category in the dataset descriptions? I can fill in the specific genres per dataset if you can set up the fields in the json-ld files.

**Comment by ddeboer** [comment]
@rschalkrce You can now add the genres to https://github.com/netwerk-digitaal-erfgoed/network-of-terms/pull/1333.

**Comment by ddeboer** [comment]
As a first step, the genres are now shown at https://termennetwerk.netwerkdigitaalerfgoed.nl/reconciliation.
